Strategy.create(description: "Abandon normal instruments")
Strategy.create(description: "Accept advice")
Strategy.create(description: "Accretion")
Strategy.create(description: "A line has two sides")
Strategy.create(description: "Allow an easement (an easement is the abandonment of a stricture)")
Strategy.create(description: "Are there sections? Consider transitions")
Strategy.create(description: "Ask people to work against their better judgment")
Strategy.create(description: "Ask your body")
Strategy.create(description: "Assemble some of the instruments in a group and treat the group")
Strategy.create(description: "Balance the consistency principle with the inconsistency principle")
Strategy.create(description: "Be dirty")
Strategy.create(description: "Breathe more deeply")
Strategy.create(description: "Bridges -build -burn")
Strategy.create(description: "Cascades")
Strategy.create(description: "Change instrument roles")
Strategy.create(description: "Change nothing and continue with immaculate consistency")
Strategy.create(description: "Children's voices -speaking -singing")
Strategy.create(description: "Cluster analysis")
Strategy.create(description: "Consider different fading systems")
Strategy.create(description: "Consult other sources -promising -unpromising")
Strategy.create(description: "Convert a melodic element into a rhythmic element")
Strategy.create(description: "Courage!")
Strategy.create(description: "Cut a vital connection")
Strategy.create(description: "Decorate, decorate")
Strategy.create(description: "Define an area as `safe' and use it as an anchor")
Strategy.create(description: "Destroy -nothing -the most important thing")
Strategy.create(description: "Discard an axiom")
Strategy.create(description: "Disconnect from desire")
Strategy.create(description: "Discover the recipes you are using and abandon them")
Strategy.create(description: "Distorting time")
Strategy.create(description: "Do nothing for as long as possible")
Strategy.create(description: "Don't be afraid of things because they're easy to do")
Strategy.create(description: "Don't be frightened of cliches")
Strategy.create(description: "Don't be frightened to display your talents")
Strategy.create(description: "Don't break the silence")
Strategy.create(description: "Don't stress one thing more than another")
Strategy.create(description: "Do something boring")
Strategy.create(description: "Do the washing up")
Strategy.create(description: "Do the words need changing?")
Strategy.create(description: "Do we need holes?")
Strategy.create(description: "Emphasize differences")
Strategy.create(description: "Emphasize repetitions")
Strategy.create(description: "Emphasize the flaws")
Strategy.create(description: "Faced with a choice, do both (given by Dieter Roth)")
Strategy.create(description: "Feedback recordings into an acoustic situation")
Strategy.create(description: "Fill every beat with something")
Strategy.create(description: "Get your neck massaged")
Strategy.create(description: "Ghost echoes")
Strategy.create(description: "Give the game away")
Strategy.create(description: "Give way to your worst impulse")
Strategy.create(description: "Go slowly all the way round the outside")
Strategy.create(description: "Honor thy error as a hidden intention")
Strategy.create(description: "How would you have done it?")
Strategy.create(description: "Humanize something free of error")
Strategy.create(description: "Imagine the music as a moving chain or caterpillar")
Strategy.create(description: "Imagine the music as a set of disconnected events")
Strategy.create(description: "Infinitesimal gradations")
Strategy.create(description: "Intentions -credibility of -nobility of -humility of")
Strategy.create(description: "Into the impossible")
Strategy.create(description: "Is it finished?")
Strategy.create(description: "Is there something missing?")
Strategy.create(description: "Is the tuning appropriate?")
Strategy.create(description: "Just carry on")
Strategy.create(description: "Left channel, right channel, center channel")
Strategy.create(description: "Listen in total darkness, or in a very large room, very quietly")
Strategy.create(description: "Listen to the quiet voice")
Strategy.create(description: "Look at a very small object; look at its center")
Strategy.create(description: "Look at the order in which you do things")
Strategy.create(description: "Look closely at the most embarrassing details and amplify them")
Strategy.create(description: "Lowest common denominator check -single beat -single note -single")
Strategy.create(description: "riff")
Strategy.create(description: "Make a blank valuable by putting it in an exquisite frame")
Strategy.create(description: "Make an exhaustive list of everything you might do and do the last")
Strategy.create(description: "thing on the list")
Strategy.create(description: "Make a sudden, destructive, unpredictable action; incorporate")
Strategy.create(description: "Mechanicalize something idiosyncratic")
Strategy.create(description: "Mute and continue")
Strategy.create(description: "Only one element of each kind")
Strategy.create(description: "(Organic) machinery")
Strategy.create(description: "Overtly resist change")
Strategy.create(description: "Put in earplugs")
Strategy.create(description: "Remember those quiet evenings")
Strategy.create(description: "Remove ambiguities and convert to specifics")
Strategy.create(description: "Remove specifics and convert to ambiguities")
Strategy.create(description: "Repetition is a form of change")
Strategy.create(description: "Reverse")
Strategy.create(description: "Short circuit")
Strategy.create(description: "improve his virility shovels them straight into his lap)")
Strategy.create(description: "Shut the door and listen from outside")
Strategy.create(description: "Simple subtraction")
Strategy.create(description: "Spectrum analysis")
Strategy.create(description: "Take a break")
Strategy.create(description: "Take away the elements in order of apparent non-importance")
Strategy.create(description: "Tape your mouth (given by Ritva Saarikko)")
Strategy.create(description: "The inconsistency principle")
Strategy.create(description: "The tape is now the music")
Strategy.create(description: "Think of the radio")
Strategy.create(description: "Tidy up")
Strategy.create(description: "Trust in the you of now")
Strategy.create(description: "Turn it upside down")
Strategy.create(description: "Twist the spine")
Strategy.create(description: "Use an old idea")
Strategy.create(description: "Use an unacceptable color")
Strategy.create(description: "Use fewer notes")
Strategy.create(description: "Use filters")
Strategy.create(description: "Use 'unqualified' people")
Strategy.create(description: "Water")
Strategy.create(description: "What are you really thinking about just now? Incorporate")
Strategy.create(description: "What is the reality of the situation?")
Strategy.create(description: "What mistakes did you make last time?")
Strategy.create(description: "What would your closest friend do?")
Strategy.create(description: "What wouldn't you do?")
Strategy.create(description: "Work at a different speed")
Strategy.create(description: "You are an engineer")
Strategy.create(description: "You can only make one dot at a time")
Strategy.create(description: "You don't have to be ashamed of using your own ideas")